### ISSUE TITLE
Change email template when erratum is received

### ISSUE THREAD

**Issue by mwvolo** [openstax/errata#1]
@openstaxalina commented on [Fri Oct 18 2019](https://github.com/openstax/business-intel/issues/710)

# Description

Focus groups such as a FAB have let us know that users would like more information about when their errata report will be reviewed and content changes made.  We are suggesting an adjustment to the email that users receive:
![errata rcvd](https://user-images.githubusercontent.com/7863733/67131154-2f8cfc00-f1c9-11e9-91ee-b0a1e29e5489.png)

The suggested correction schedule text is:

_Errata received from March to October will be reflected in the following formats for the spring semester: web view, OpenStax + SE app, Kindle, and iBook if applicable._

_Errata received from November to February will be reflected in the following formats for the fall semester: web view, OpenStax + SE app, Kindle, and iBook if applicable._

_Instructor and student resources, such as test banks and student solution manuals, also follow the schedule above._

_In an effort to keep PDF versions aligned with printed books, PDF versions of OpenStax textbooks are only updated, prior to the fall semester, if there are substantial errata updates to the book that year.  Click the “Sign up to learn more” link on your book’s page to be notified of PDF updates and other news._

This would make the email quite long as currently placed in the screenshot, so perhaps there is a better way to convey this info...   

# Acceptance Criteria

User has access to errata review/implementation timeline info within their confirmation email. 

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Approvals
1A-DEFINE
- [ ] PDM approves UX LoFi Design

1C-DESIGN
  - [ ] PDM approves UX HiFi Design

4A-UX REV
  - [ ] UX approves change
  - [ ] PDM approves change

# Process 
[Work Management for BIT](https://github.com/openstax/business-intel/blob/master/CONTRIBUTING.md)

---

@openstaxalina commented on [Fri Oct 18 2019](https://github.com/openstax/business-intel/issues/710#issuecomment-543973536)

Assigning to @allisonhowell for messaging/UX (?) review and priority...

**Comment by yblock** [comment]
The email being sent will change depending on when it was created. Will test on dev once merged and deployed.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
