### ISSUE TITLE
Fix logic of save and send email button

### ISSUE THREAD

**Issue by yblock** [openstax/errata#10]
@yblock commented on [Thu Nov 14 2019](https://github.com/openstax/os-webview/issues/1618)

The current JavaScript is changing the button to say it is sending an email if either of the fields "Status" or "Resolution" are changed. An email is not always sent, this should be changed to only report that an email is being sent in the cases that an email is actually being sent.

**Comment by yblock** [comment]
Verified in QA @Brooke-Fail

**Comment by yblock** [comment]
This will require collect static to be ran when merged to prod (if that isn’t already an automated process)

**Comment by yblock** [comment]
verified on staging @Brooke-Fail

**Comment by Brooke-Fail** [comment]
Verified in Production.
