### ISSUE TITLE
Add tooltips to various fields

### ISSUE THREAD

**Issue by openstaxalina** [openstax/errata#11]
@openstaxalina commented on [Wed Nov 20 2019](https://github.com/openstax/business-intel/issues/759)

# Description

**SCENARIO** _Briefly describe the issue._

It seems that if an errata report is marked as a duplicate and saved, then changed to no longer be a duplicate, the report page will continue to show that report as a duplicate.  (Note: the "duplicate" message persisted even after clearing browser cache.)

----------------
**Steps to Reproduce the issue:** _Who, Where and How?_

1) submit a test errata report
2) mark report as duplicate, save
3) note the Resolution Notes "This is a duplicate of report  [#]."
4) mark the report as something else (such as reviewed / will not fix), save
5) note that Resolution Notes continue to indicate the errata report is a duplicate

- **User Type:**
` [ ] ` Admin  ` [ ] ` Content/QA
` [ ] ` Student  ` [ ] ` Teacher
` [x] ` N/A
- **Username:** any
- **URL:**  varies
- **Course number:**  N/A
- **Course type:**  N/A

----------------
**Environment:**

- **Instance:**
` [x] ` production ` [ ] ` qa ` [ ] ` staging
` [ ] ` dev ` [ ] ` content ` [ ] ` demo
- **OS:**
` [x] ` Mac OSX ` [ ] ` Windows
` [ ] ` Android ` [ ] ` iOS
- **Browser:**
` [x] ` Chrome ` [ ] ` Firefox ` [x] ` Safari
` [ ] ` Opera ` [ ] ` IE ` [ ] ` Edge
- **Browser Version:**  

----------------
**Possible impact on a User:**

If we incorrectly mark a report as a duplicate, we can undo this in the CMS, but not from the user's perspective.  Users may become confused or frustrated.

----------------
**Images or Screenshots** (_attach below_)

# Approvals
1A-DEFINE
- [ ] PDM approves UX LoFi Design

1C-DESIGN
  - [ ] PDM approves UX HiFi Design

4A-UX REV
  - [ ] UX approves change
  - [ ] PDM approves change

# Process 
[Work Management for BIT](https://github.com/openstax/business-intel/blob/master/CONTRIBUTING.md)

---

@openstaxalina commented on [Wed Nov 20 2019](https://github.com/openstax/business-intel/issues/759#issuecomment-556347954)

@yblock is this something that you would be able to look at?

**Comment by yblock** [comment]
This is because the "resolution notes" field that feeds into the online errata view for the customer is auto-populated with hard-coded text. I will park this with the team to see how they want to handle this functionality.

**Comment by lwtchu** [comment]
Compromise: Maybe add a tool tip to teach people who to make sure the text gets the default. Aka leaving it blanks will auto-fill with something new.

**Comment by yblock** [comment]
worked with Larissa in-person to come up with tooltip text for some fields.

**Comment by Brooke-Fail** [comment]
Verified in that the tooltip is there in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
