### ISSUE TITLE
Tweaks to Errata Submission Reviewed Email

### ISSUE THREAD

**Issue by openstaxalina** [openstax/errata#12]
I am requesting a couple changes to the work done for #2: 
- newline markup needs to be removed/fixed
- change to the start of the second paragraph
![ErrataSubmissionReviewedEmail](https://user-images.githubusercontent.com/7863733/69275528-33ce7f80-0ba2-11ea-95cd-b511b4a567f4.png)

**Comment by lwtchu** [comment]
DID YOU KNOW.

We can change it. 

Here: https://openstax.org/django-admin/errata/emailtext/4/change/

<blockquote><img src="https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/static/wagtailadmin/images/favicon.ico" width="48" align="right"><div><strong><a href="https://openstax.org/django-admin/errata/emailtext/4/change/">Wagtail - Sign in</a></strong></div></blockquote>

**Comment by lwtchu** [comment]
@openstaxalina i made the change. do you wanna test it again?

**Comment by yblock** [comment]
I also added a couple of ```<br/>``` for the line breaks. return lines are not read at html

**Comment by openstaxalina** [comment]
Looks great, thank you!

<img width="559" alt="Screen Shot 2019-11-20 at 2 35 54 PM" src="https://user-images.githubusercontent.com/7863733/69275965-1352f500-0ba3-11ea-8163-20f3f87ac780.png">

In the future, who will be the point person for such changes?  In this case, all three of us went in there to make the change.  I propose that Colby owns this type of change.

**Comment by yblock** [comment]
sounds good, and you both still have the ability if I'm not available.
