### ISSUE TITLE
Reviewed/Will Correct Dates Seem to be a Day Behind

### ISSUE THREAD

**Issue by openstaxalina** [openstax/errata#13]
I submitted this test report on 11/20 and moved it to reviewed and approved in the CMS for testing purposes.  It looks like somehow those changes are being recorded as happening before I submitted the report:

<img width="1279" alt="Screen Shot 2019-11-20 at 2 31 24 PM" src="https://user-images.githubusercontent.com/7863733/69275737-9889da00-0ba2-11ea-82af-0a75960a8e8a.png">

@yblock would you be able to investigate this?

**Comment by yblock** [comment]
@mwharrison do you know why this would be, or is this a Roy question? The created and modified dates look to be correct in admin.

test issue:
https://openstax.org/django-admin/errata/errata/10343/change/ 

<blockquote><img src="https://d3bxy9euw4e147.cloudfront.net/oscms-prodcms/static/wagtailadmin/images/favicon.ico" width="48" align="right"><div><strong><a href="https://openstax.org/django-admin/errata/errata/10343/change/">Wagtail - Sign in</a></strong></div></blockquote>

**Comment by mwvolo** [comment]
@yblock are they a day behind or using UTC time?
It's more likely a server time issue.

**Comment by yblock** [comment]
@mwharrison who do you mean by "they"?

**Comment by mwvolo** [comment]
Going to add timezone offset to the `resolution_date` in the BE.

**Comment by yblock** [comment]
Brooke is saying that when she creates a new errata in testing that the reviewed date shows a day before still. Ideas?

**Comment by yblock** [comment]
verified that the times are -6 (CST), but this did not resolve the issue. Still making this change though. A new card will be opened for front-end work.
