### ISSUE TITLE
Tweak to Wording in Errata Received Email

### ISSUE THREAD

**Issue by openstaxalina** [openstax/errata#14]
I am requesting two slight tweaks to my own wording from #1, to be consistent with other language used on openstax.org:
![ErrataReceivedEmail](https://user-images.githubusercontent.com/7863733/69276569-59f51f00-0ba4-11ea-9d0f-42100ad96449.png)

**Comment by yblock** [comment]
done

**Comment by openstaxalina** [comment]
@yblock can you make one more tweak in the above screenshot?  I modified it after submitting the issue, but I wasn't quick enough 🐎
