### ISSUE TITLE
Show faculty-verified status on errata csv

### ISSUE THREAD

**Issue by openstaxalina** [openstax/errata#15]
The errata csv export should include a column indicating whether the submitter is faculty-verified.  This could be a "yes/no", 1 or 0, or just display the submitter's name or email if they are faculty-verified.

**Comment by yblock** [comment]
KeyError for 'user_faculty_status' when trying to run report. Need to investigate further.

**Comment by yblock** [comment]
the report now runs without error, but I'll have to wait until this code is on dev to know if it is pulling the account data properly.

**Comment by yblock** [comment]
verified on QA @Brooke-Fail

**Comment by yblock** [comment]
Verified this did not cause regressions on staging, however it is not pulling the info into the newly created column. Not a show-stopper, and still fine for release. I'll make a new card to continue working on this feature.

**Comment by Brooke-Fail** [comment]
Verified in Production.
