### ISSUE TITLE
display submitter Name to SME reviewer

### ISSUE THREAD

**Issue by yblock** [openstax/errata#16]
Building on previous user_faculty_status work, find a way to display user's name based on submitter's faculty status and current account viewer's group memberships.

**Comment by yblock** [comment]
modify to always display these fields to Content Mangers (they should all be FERPA certified)

**Comment by yblock** [comment]
CS uses the accounts link, so does not need to be included in this

**Comment by openstaxalina** [comment]
I updated the title and description to reflect that we should only show the user's name, not email -- and all of this is only for faculty-verified users.

**Comment by yblock** [comment]
closing this as we decided not to apply user-information on errata unless specifically requested, in which case a manual report can be generated
