### ISSUE TITLE
Change email template when erratum is reviewed

### ISSUE THREAD

**Issue by mwvolo** [openstax/errata#2]
@openstaxalina commented on [Fri Oct 18 2019](https://github.com/openstax/business-intel/issues/711)

# Description

With the changes in REX and others we are requesting on the tool, we (content) recommend the following changes for the email a user receives when we have reviewed their errata submission and noted that changes are "approved" (not "completed", but approved to make)

Note that it may make sense to add an additional reminder of our correction schedule, (see #710) 
![errata-reviewed-email](https://user-images.githubusercontent.com/7863733/67131497-8515d880-f1ca-11e9-808d-323fc322c1af.png)

# Acceptance Criteria
User receives clear, accurate information with their reviewed/approved for change email
(suggested) user is reminded of errata correction schedule in email

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Approvals
1A-DEFINE
- [ ] PDM approves UX LoFi Design

1C-DESIGN
  - [ ] PDM approves UX HiFi Design

4A-UX REV
  - [ ] UX approves change
  - [ ] PDM approves change

# Process 
[Work Management for BIT](https://github.com/openstax/business-intel/blob/master/CONTRIBUTING.md)

---

@openstaxalina commented on [Fri Oct 18 2019](https://github.com/openstax/business-intel/issues/711#issuecomment-543976631)

Assigning to @allisonhowell for messaging/UX (?) review and priority...

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
