### ISSUE TITLE
Add "number of errors" to errata list view

### ISSUE THREAD

**Issue by yblock** [openstax/errata#20]
@yblock commented on [Fri Dec 06 2019](https://github.com/openstax/os-webview/issues/1632)

---

@staxly[bot] commented on [Fri Dec 06 2019](https://github.com/openstax/os-webview/issues/1632#issuecomment-562680403)

The maintainers of this repository would appreciate it if you could provide more information.

**Comment by lwtchu** [comment]
** Note for larissa: This is to make it reportable.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
