### ISSUE TITLE
Change: "Number of errors" - no negatives and default to 1

### ISSUE THREAD

**Issue by lwtchu** [openstax/errata#21]
Change request for "Number of Error" field to default to 1 and to not have negatives or 0.

POSITIVE INTEGER FIELD?? wahtever that number is called. i'm bad at math

WHY????
https://github.com/openstax/errata/issues/20 - since this is reportable. it'll be nice if it could be added up instead of default blank

**Comment by mwvolo** [comment]
@lwtchu - can you provide a screenshot of the problem?

**Comment by yblock** [comment]
This is the field she is referring to:

![Screen Shot 2019-12-10 at 1 47 01 PM](https://user-images.githubusercontent.com/5865292/70563292-98eb1480-1b53-11ea-8bce-193dfe586a25.png)

it is an IntegerField() that accepts negative numbers and does not have a default value.

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
