### ISSUE TITLE
unable to run large report on errata

### ISSUE THREAD

**Issue by yblock** [openstax/errata#28]
cloudfront serves a 504 error, I imagine this it from the large amount of time accounts takes to respond to each faculty_status_info request.

**Comment by yblock** [comment]
504 ERROR
The request could not be satisfied.
CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

Generated by cloudfront (CloudFront)
Request ID: ABFa4nmxYiHFLs6RNipogJ6IRkU6xfNl1USVV8gGA8MyXr9uvFEs0w==

**Comment by Brooke-Fail** [comment]
Verified in Staging you can export a large errata report.

**Comment by Brooke-Fail** [comment]
Verified in Production.
