### ISSUE TITLE
Disable "Your Correction is Live" Emails

### ISSUE THREAD

**Issue by mwvolo** [openstax/errata#3]
@openstaxalina commented on [Fri Oct 18 2019](https://github.com/openstax/business-intel/issues/712)

# Description

We would like to stop sending these emails in favor of more prominently surfacing the correction schedule (see #709, #710, and #711) **and** putting the semester in which the correction will appear on the errata list (see #713 ).  

# Acceptance Criteria
- moving reports to Approved/Completed no longer sends a "Your correction is live" email

# Acceptance Tests

derive these from "Acceptance Criteria" during "Design" phase

**title**: template  
> GIVEN something  
> AND something else  
> WHEN something  
> AND something else  
> THEN something  
> AND something else  

# Approvals
1A-DEFINE
- [ ] PDM approves UX LoFi Design

1C-DESIGN
  - [ ] PDM approves UX HiFi Design

4A-UX REV
  - [ ] UX approves change
  - [ ] PDM approves change

# Process 
[Work Management for BIT](https://github.com/openstax/business-intel/blob/master/CONTRIBUTING.md)

---

@openstaxalina commented on [Fri Oct 18 2019](https://github.com/openstax/business-intel/issues/712#issuecomment-543977877)

Assigning to @allisonhowell for messaging/UX (?) review and priority...

**Comment by Brooke-Fail** [comment]
Verified in QA.

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Verified in Production.
