### ISSUE TITLE
Errata messaging/workflow changes for books getting a new edition

### ISSUE THREAD

**Issue by openstaxalina** [openstax/errata#30]
To manage maintenance effort and costs, we will no longer review and correct errata when the book is slated for a new edition within 18 months.  Currently this applies to:

- _Introduction to Sociology 2e_
- _American Government 2e_

...both of which are slated for new editions by March 2021.  **The changes below should only be applied to those two books.**  It might be good to create some kind of category for books with upcoming editions so they can be added to this list (as we decide to make new editions) and get the treatment below.

I am using this card to document all the changes I could think of.  Ultimately we may need to break this card up into smaller tasks, possibly in different repos.

- [x] **errata submission confirmation email**

Change

`Errata received from March to October will be reflected in the following formats for the spring semester: web view, OpenStax + SE app, Kindle, and iBook if applicable.`

`Errata received from November to February will be reflected in the following formats for the fall semester: web view, OpenStax + SE app, Kindle, and iBook if applicable.`

`Instructor and student resources, such as test banks and student solution manuals, also follow the schedule above.`

`In an effort to keep PDF versions aligned with printed books, PDF versions of OpenStax textbooks are only updated, prior to the fall semester, if there are substantial errata updates to the book that year. Click the “Sign up to learn more” link on your book’s page to be notified of PDF updates and other news.`

to 

`This book is scheduled for a new edition.  Errata reports will be evaluated for implementation in the new edition.  Click the “Sign up to learn more” link on your book’s page to be notified of the upcoming edition and other news.`

- [ ] **errata submission reviewed email**
Change

`...that a change will be made.`

to 

`...that a change will be made in the new edition of this book.`

- [x] would like to get Colby's thoughts to see if I missed any messaging that would need updated.

**Comment by openstaxalina** [comment]
@yblock this is approved and ready for work.  I have modified the card to include only the email updates.  I've opened [this card](https://github.com/openstax/business-intel/issues/853) to capture the front end updates.

**Comment by yblock** [comment]
this will require a migration, as well as a collectstatic to be run when on prod

**Comment by Brooke-Fail** [comment]
Verified in Staging.

**Comment by Brooke-Fail** [comment]
Staging verification is good for this.
