### ISSUE TITLE
"technical error" case should send an email 

### ISSUE THREAD

**Issue by yblock** [openstax/errata#39]
Like the "partner product" case, "technical error" should also send an email when marked complete.  

There should also be a "base-case" generic email send to any submitter when the errata is marked "completed"

**Comment by yblock** [comment]
migration required

2 new email cases will also have text added upon deployment

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
