### ISSUE TITLE
Upcoming edition email 

### ISSUE THREAD

**Issue by yblock** [openstax/errata#43]
After new book states are sorted, use book state to determine which email is sent for upcoming new edition ... currently hardcoded to send a different email for sociology 2e and amgov 2e

![Screen Shot 2020-06-04 at 9.57.38 AM.png](https://images.zenhubusercontent.com/5c5227f6f3a9152a2050e821/fbc870f6-0fe8-49ad-ae98-2271611ce82a)

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
No books meet this criteria in Production. Verified in Staging, closing.
