### ISSUE TITLE
modify/add editorial review statuses 

### ISSUE THREAD

**Issue by lwtchu** [openstax/errata#47]
this way we don't have the same pile of new errata that we're holding for anthony sitting in new.

internal editorial review status hsould map the same as k12 editorial review and regular editorial review.

WE ARE CALLING IT

Internal Editorial Review

**Comment by yblock** [comment]
**this does have a migration** 

for funct ver, there should be new statuses in the drop down menu "Andrew Editorial Review" and "Anthony Editorial Review"

**Comment by yblock** [comment]
Making some changes to this: 

Leaving Editorial Review status the same
Changing K-12 Editorial Review to Andrew Editorial Review
Adding a new status Anthony Editorial Review 


Roy says that as long as the status has "Editorial Review" in it, it should filter on the FE errata list correctly

**Comment by brittanyearly** [comment]
Verified in Production.
