### ISSUE TITLE
front end mapping for new internal editorial review status

### ISSUE THREAD

**Issue by lwtchu** [openstax/errata#48]
see #47 

should map to the same as editorial review and k12 editorial review

WE ARE CALLING IT

Internal Editorial Review

**Comment by yblock** [comment]
@RoyEJohnson This is the same thing as the K-12 Editorial Review status. I've added the status "Internal Editorial Review"

**Comment by yblock** [comment]
Here is an erratum on dev with the new status as you requested for the other one: https://cms-dev.openstax.org/django-admin/errata/errata/7266

**Comment by RoyEJohnson** [comment]
I've updated my fix to look for "Editorial Review" regardless of anything else, so you can have all the different kinds of Editorial Review you want.

**Comment by yblock** [comment]
Haha, perfect!
