### ISSUE TITLE
Show Additional Location Information Field in Errata Tool Export

### ISSUE THREAD

**Issue by openstaxalina** [openstax/errata#49]
Please add the additional location field to the export in the errata tool. This will address the following issue submitted by Wisewire:

As we’ve started to process the next batch of errata, we noticed that the newer “additional location information” field users can fill in when they submit errata is not exported from the errata tool when we download the excel sheet of reports. It looks like only the main location field is exported. Is there any way to update the export sheet to include the additional location information field?
 
The new field is great to have and will save our team time locating issues, but currently, the only way we can see that is to open each report in the errata tool.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
