### ISSUE TITLE
"Additional location information" isn't shown in the errata list or in the errata submission details

### ISSUE THREAD

**Issue by jody-frankowski** [openstax/errata#50]
Because "Additional location information" isn't shown in the errata list or in the errata submission details, it makes searching for existing errata harder.
Eg., for the errata I submitted, I almost always put the "Try It" or "Example" number in this field, and if someone else had done the same, I may not be able to find his submission in the list.

**Comment by yblock** [comment]
Thank you for bringing this to our attention. We will take a look and see what the best way of making this field available is. I will be closing this issue, but we will continue working on it internally.
