### ISSUE TITLE
Autofill assessment errata fields 

### ISSUE THREAD

**Issue by yblock** [openstax/errata#52]
If the errata comes from tutor and has the format ####@  in the additional information field, auto select that it is an assessment errata and fill in the ID from the additional information field.

**Comment by brittanyearly** [comment]
Verified in QA. 1372@11 18.2 Formation of New Species (for Staging testing).

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
