### ISSUE TITLE
Mass mark as complete

### ISSUE THREAD

**Issue by lwtchu** [openstax/errata#7]
- Select more than one errata
- Go to actions and mark as complete
- Complete with warnings and a confirmation box ("Type: Colby is the best co-worker I could ever have." in order to make the change). 
- Only CMs can do this

**Comment by yblock** [comment]
@lwtchu 

I noticed that all of the "mass mark as..." actions are available to user accounts that are flagged as staff (which allows them to see the admin page. Is this barrier enough or do I need to find a way to lock all of those options down to only allow CMs to use them?

**Comment by yblock** [comment]
From Larissa:
Pull out vendors into their own group and only allow them to see the "run report" option in the errata actions list if possible.

**Comment by yblock** [comment]
To test, the account will need to have the 'Content Manager' group added as well as errata permissions to view, add, and delete

**Comment by yblock** [comment]
verified on QA @Brooke-Fail

**Comment by yblock** [comment]
verified on staging @Brooke-Fail

**Comment by Brooke-Fail** [comment]
Verified in Production.
