### ISSUE TITLE
Update a few errata resolution reponses

### ISSUE THREAD

**Issue by yblock** [openstax/errata#74]
Some of the auto-fill resolution responses for errata need to be updated. Changes as follows:

Current responses:

**Not An Error** - "Our reviewers determined this was not an error."
Our reviewers determined this was not an error in the most current version of the book’s content. It’s possible that you are using an old version of the content via a PDF or printed text. If possible, please double check that you see the error in the web version of the book, and provide a screenshot and more detail if you believe we have made a mistake.

If status is **Reviewed** or **Completed** and resolution is **Approved** - "Our reviewers accepted this change. "
Our reviewers accepted this change, and it will be included in the next print cycle.

If status is **Completed** and resolution is **Sent to Customer Support** - "Thank you for this feedback. Your report has been escalated to our Support team. A member of the Support team will contact you with further details."
Thank you for this feedback. Your report has been escalated to our Customer Service team and they will contact you with further details.

**Comment by brittanyearly** [comment]
Verified in QA.

**Comment by brittanyearly** [comment]
Verified in Staging.

**Comment by brittanyearly** [comment]
Verified in Production.
