### ISSUE TITLE
Set up a "Kelsey Editorial Review" In Errata tool

### ISSUE THREAD

**Issue by yblock** [openstax/errata#77]
There should be a new status for "Kelsey Editorial Review"

While I'm in there, I'll also be renaming "Andrew editorial review" to "K-12 editorial review"

## For QA testing:
**This will have migrations.** 

When testing, you should see that "Andrew Editorial Review" has been renamed to "K-12 Editorial Review".

When testing, you should see a new status names "Kelsey Editorial Review"

**Comment by yblock** [comment]
@brittanyearly this looks like it's already in production?

**Comment by brittanyearly** [comment]
@yblock yes, I do see a "Kelsey" option in production.

**Comment by yblock** [comment]
verified in production, all bueno
