### ISSUE TITLE
Rename errata statuses 

### ISSUE THREAD

**Issue by yblock** [openstax/errata#79]
Kelsey and Anthony statuses need to be updated to be more generic and have a wider scopes. 

Kelsey Editorial Review -> Cartridge Review (internally and externally)
Anthony Editorial Review -> OpenStax Editorial Review (internally) and Editorial Review (externally)

**Before release of this code, I'd like to move the few errata that are in the old statuses to a different one that already exists as a placeholder so we don't have to deal with migrating the status in the database. Once the code is released, I'll just manually move the errata into their new status homes.**

**Comment by brittanyearly** [comment]
Thank you @yblock , this will be Released 07/27/2022. I will message via Slack around deployment.

**Comment by brittanyearly** [comment]
Verified in Production.
